name: CI

on:
  push:
    branches: [release]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Publish NuGet
        run: |
          dotnet pack -c Release
          dotnet nuget push *.nupkg
