name: CI

on:
  push:
    branches:
      - master

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
      - run: dotnet pack -c Release --version-suffix "$BUILD_NUMBER"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          source-url: https://nuget.pkg.github.com/MarcinWorkDev/index.json
      - run: dotnet nuget push **/.nupkg
      #- run: nuget setapikey ${{secrets.github_token}} -Source https://nuget.pkg.github.com/MarcinWorkDev/
      #- run: nuget push **/*.nupkg -Source https://nuget.pkg.github.com/MarcinWorkDev/
