name: CI

on:
  push:
    branches:
      - master

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
      - run: dotnet pack -c Release --version-suffix "$BUILD_NUMBER"
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget push **/*.nupkg "${{secrets.github_token}}" -Source "https://nuget.pkg.github.com/MarcinWorkDev/index.json"
