name: CI

on:
  push:
    branches:
      - master

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish NuGet
        run: |
          dotnet pack -c Release
          dotnet nuget push *.nupkg
