name: CI

on:
  push:
    branches: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish NuGet
      run: |
        ls
        dotnet pack -c Release
        dotnet nuget push *.nupkg
