name: CI

on:
  push:
    branches:
      - master

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: dotnet pack -c Release
      - run: dotnet nuget push *.nupkg -s 'https://nuget.pkg.github.com/MarcinWorkDev/index.json' -k '${{ secrets.GITHUB_TOKEN }}'
